openapi: 3.0.3
info:
  title: Aforro Backend API
  version: 1.0.0
  description: Aforro Backend Developer Assignment
paths:
  /api/orders/:
    post:
      operationId: orders_create
      tags:
      - orders
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/OrderCreate'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/OrderCreate'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/OrderCreate'
        required: true
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OrderResponse'
          description: ''
  /api/schema/:
    get:
      operationId: schema_retrieve
      description: |-
        OpenApi3 schema for this API. Format can be selected via content negotiation.

        - YAML: application/vnd.oai.openapi
        - JSON: application/vnd.oai.openapi+json
      parameters:
      - in: query
        name: format
        schema:
          type: string
          enum:
          - json
          - yaml
      - in: query
        name: lang
        schema:
          type: string
          enum:
          - af
          - ar
          - ar-dz
          - ast
          - az
          - be
          - bg
          - bn
          - br
          - bs
          - ca
          - ckb
          - cs
          - cy
          - da
          - de
          - dsb
          - el
          - en
          - en-au
          - en-gb
          - eo
          - es
          - es-ar
          - es-co
          - es-mx
          - es-ni
          - es-ve
          - et
          - eu
          - fa
          - fi
          - fr
          - fy
          - ga
          - gd
          - gl
          - he
          - hi
          - hr
          - hsb
          - ht
          - hu
          - hy
          - ia
          - id
          - ig
          - io
          - is
          - it
          - ja
          - ka
          - kab
          - kk
          - km
          - kn
          - ko
          - ky
          - lb
          - lt
          - lv
          - mk
          - ml
          - mn
          - mr
          - ms
          - my
          - nb
          - ne
          - nl
          - nn
          - os
          - pa
          - pl
          - pt
          - pt-br
          - ro
          - ru
          - sk
          - sl
          - sq
          - sr
          - sr-latn
          - sv
          - sw
          - ta
          - te
          - tg
          - th
          - tk
          - tr
          - tt
          - udm
          - ug
          - uk
          - ur
          - uz
          - vi
          - zh-hans
          - zh-hant
      tags:
      - schema
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/vnd.oai.openapi:
              schema:
                type: object
                additionalProperties: {}
            application/yaml:
              schema:
                type: object
                additionalProperties: {}
            application/vnd.oai.openapi+json:
              schema:
                type: object
                additionalProperties: {}
            application/json:
              schema:
                type: object
                additionalProperties: {}
          description: ''
  /api/search/products/:
    get:
      operationId: search_products_list
      parameters:
      - in: query
        name: category
        schema:
          type: integer
        description: Category ID
      - in: query
        name: in_stock
        schema:
          type: boolean
        description: Filter by stock availability
      - in: query
        name: max_price
        schema:
          type: number
          format: double
        description: Maximum price
      - in: query
        name: min_price
        schema:
          type: number
          format: double
        description: Minimum price
      - in: query
        name: page
        schema:
          type: integer
        description: Page number
      - in: query
        name: page_size
        schema:
          type: integer
        description: Number of results per page
      - in: query
        name: q
        schema:
          type: string
        description: Search keyword
      - in: query
        name: sort
        schema:
          type: string
          enum:
          - newest
          - price
          - relevance
        description: Sorting
      - in: query
        name: store_id
        schema:
          type: integer
        description: Store ID
      tags:
      - search
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ProductSearch'
          description: ''
  /api/search/suggest/:
    get:
      operationId: search_suggest_list
      parameters:
      - in: query
        name: q
        schema:
          type: string
        description: Search term. Minimum 3 characters.
        required: true
      tags:
      - search
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Suggestion'
          description: ''
  /api/stores/{store_id}/inventory/:
    get:
      operationId: stores_inventory_list
      parameters:
      - in: path
        name: store_id
        schema:
          type: integer
        required: true
      tags:
      - stores
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Inventory'
          description: ''
  /api/stores/{store_id}/orders/:
    get:
      operationId: stores_orders_list
      parameters:
      - in: path
        name: store_id
        schema:
          type: integer
        required: true
      tags:
      - stores
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Order'
          description: ''
components:
  schemas:
    Inventory:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        product:
          type: integer
        product_title:
          type: string
          readOnly: true
        product_price:
          type: string
          format: decimal
          pattern: ^-?\d{0,8}(?:\.\d{0,2})?$
          readOnly: true
        category_name:
          type: string
          readOnly: true
        quantity:
          type: integer
          maximum: 9223372036854775807
          minimum: 0
          format: int64
      required:
      - category_name
      - id
      - product
      - product_price
      - product_title
    Order:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        store:
          type: integer
        status:
          $ref: '#/components/schemas/StatusEnum'
        created_at:
          type: string
          format: date-time
          readOnly: true
        items:
          type: array
          items:
            $ref: '#/components/schemas/OrderItem'
          readOnly: true
        total_items:
          type: integer
          readOnly: true
      required:
      - created_at
      - id
      - items
      - store
      - total_items
    OrderCreate:
      type: object
      properties:
        store_id:
          type: integer
        items:
          type: array
          items:
            $ref: '#/components/schemas/OrderItemInput'
      required:
      - items
      - store_id
    OrderItem:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        product:
          type: integer
        product_title:
          type: string
          readOnly: true
        quantity_requested:
          type: integer
          maximum: 9223372036854775807
          minimum: 0
          format: int64
      required:
      - id
      - product
      - product_title
      - quantity_requested
    OrderItemInput:
      type: object
      properties:
        product_id:
          type: integer
        quantity_requested:
          type: integer
          minimum: 1
      required:
      - product_id
      - quantity_requested
    OrderResponse:
      type: object
      properties:
        message:
          type: string
        status:
          type: string
        insufficient_stock:
          type: array
          items:
            type: object
            additionalProperties: {}
        order:
          $ref: '#/components/schemas/Order'
      required:
      - message
      - order
      - status
    ProductSearch:
      type: object
      properties:
        id:
          type: integer
        title:
          type: string
        description:
          type: string
          nullable: true
        price:
          type: string
          format: decimal
          pattern: ^-?\d{0,8}(?:\.\d{0,2})?$
        category:
          type: string
        inventory_quantity:
          type: integer
          nullable: true
        created_at:
          type: string
          format: date-time
      required:
      - category
      - created_at
      - description
      - id
      - price
      - title
    StatusEnum:
      enum:
      - PENDING
      - CONFIRMED
      - REJECTED
      type: string
      description: |-
        * `PENDING` - Pending
        * `CONFIRMED` - Confirmed
        * `REJECTED` - Rejected
    Suggestion:
      type: object
      properties:
        title:
          type: string
      required:
      - title
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic
    cookieAuth:
      type: apiKey
      in: cookie
      name: sessionid
